# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  govuk-notify-comms:
    build:
      target: development
    image: govuk-notify-comms-development
    container_name: govuk-notify-comms-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    networks:
      - govuk-notify-comms

networks:
  govuk-notify-comms:
    name: govuk-notify-comms
    driver: bridge
